// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesOrderManager.Api.Models;

#nullable disable

namespace SalesOrderManager.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230203142853_Initial DB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SalesOrderManager.Shared.Domain.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            Name = "Belgium"
                        },
                        new
                        {
                            CountryId = 2,
                            Name = "Germany"
                        },
                        new
                        {
                            CountryId = 3,
                            Name = "Netherlands"
                        },
                        new
                        {
                            CountryId = 4,
                            Name = "USA"
                        },
                        new
                        {
                            CountryId = 5,
                            Name = "Japan"
                        },
                        new
                        {
                            CountryId = 6,
                            Name = "China"
                        },
                        new
                        {
                            CountryId = 7,
                            Name = "UK"
                        },
                        new
                        {
                            CountryId = 8,
                            Name = "France"
                        },
                        new
                        {
                            CountryId = 9,
                            Name = "Brazil"
                        });
                });

            modelBuilder.Entity("SalesOrderManager.Shared.Domain.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("JoinedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Smoker")
                        .HasColumnType("bit");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("CountryId");

                    b.HasIndex("JobCategoryId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            BirthDate = new DateTime(1979, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Brussels",
                            Comment = "Lorem Ipsum",
                            CountryId = 1,
                            Email = "bethany@bethanyspieshop.com",
                            FirstName = "Bethany",
                            Gender = 1,
                            JobCategoryId = 1,
                            JoinedDate = new DateTime(2015, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Smith",
                            Latitude = 50.850299999999997,
                            Longitude = 4.3517000000000001,
                            MaritalStatus = 1,
                            PhoneNumber = "324777888773",
                            Smoker = false,
                            Street = "Grote Markt 1",
                            Zip = "1000"
                        });
                });

            modelBuilder.Entity("SalesOrderManager.Shared.Domain.JobCategory", b =>
                {
                    b.Property<int>("JobCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobCategoryId"), 1L, 1);

                    b.Property<string>("JobCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobCategoryId");

                    b.ToTable("JobCategories");

                    b.HasData(
                        new
                        {
                            JobCategoryId = 1,
                            JobCategoryName = "Pie research"
                        },
                        new
                        {
                            JobCategoryId = 2,
                            JobCategoryName = "Sales"
                        },
                        new
                        {
                            JobCategoryId = 3,
                            JobCategoryName = "Management"
                        },
                        new
                        {
                            JobCategoryId = 4,
                            JobCategoryName = "Store staff"
                        },
                        new
                        {
                            JobCategoryId = 5,
                            JobCategoryName = "Finance"
                        },
                        new
                        {
                            JobCategoryId = 6,
                            JobCategoryName = "QA"
                        },
                        new
                        {
                            JobCategoryId = 7,
                            JobCategoryName = "IT"
                        },
                        new
                        {
                            JobCategoryId = 8,
                            JobCategoryName = "Cleaning"
                        },
                        new
                        {
                            JobCategoryId = 9,
                            JobCategoryName = "Bakery"
                        });
                });

            modelBuilder.Entity("SalesOrderManager.Shared.Domain.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StateId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("StateId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            Name = "New York Building 1",
                            StateId = 28
                        },
                        new
                        {
                            OrderId = 2,
                            Name = "California Hotel AJK",
                            StateId = 5
                        });
                });

            modelBuilder.Entity("SalesOrderManager.Shared.Domain.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StateId");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            StateId = 1,
                            Name = "AL"
                        },
                        new
                        {
                            StateId = 2,
                            Name = "AK"
                        },
                        new
                        {
                            StateId = 3,
                            Name = "AZ"
                        },
                        new
                        {
                            StateId = 4,
                            Name = "AR"
                        },
                        new
                        {
                            StateId = 5,
                            Name = "CA"
                        },
                        new
                        {
                            StateId = 6,
                            Name = "CO"
                        },
                        new
                        {
                            StateId = 7,
                            Name = "CT"
                        },
                        new
                        {
                            StateId = 8,
                            Name = "DE"
                        },
                        new
                        {
                            StateId = 9,
                            Name = "DC"
                        },
                        new
                        {
                            StateId = 10,
                            Name = "FL"
                        },
                        new
                        {
                            StateId = 11,
                            Name = "GA"
                        },
                        new
                        {
                            StateId = 12,
                            Name = "HI"
                        },
                        new
                        {
                            StateId = 13,
                            Name = "ID"
                        },
                        new
                        {
                            StateId = 14,
                            Name = "IL"
                        },
                        new
                        {
                            StateId = 15,
                            Name = "IN"
                        },
                        new
                        {
                            StateId = 16,
                            Name = "IA"
                        },
                        new
                        {
                            StateId = 17,
                            Name = "KS"
                        },
                        new
                        {
                            StateId = 18,
                            Name = "KY"
                        },
                        new
                        {
                            StateId = 19,
                            Name = "LA"
                        },
                        new
                        {
                            StateId = 20,
                            Name = "ME"
                        },
                        new
                        {
                            StateId = 21,
                            Name = "MD"
                        },
                        new
                        {
                            StateId = 22,
                            Name = "MA"
                        },
                        new
                        {
                            StateId = 23,
                            Name = "MI"
                        },
                        new
                        {
                            StateId = 24,
                            Name = "MN"
                        },
                        new
                        {
                            StateId = 25,
                            Name = "MS"
                        },
                        new
                        {
                            StateId = 26,
                            Name = "MO"
                        },
                        new
                        {
                            StateId = 27,
                            Name = "MT"
                        },
                        new
                        {
                            StateId = 28,
                            Name = "NY"
                        });
                });

            modelBuilder.Entity("SalesOrderManager.Shared.Domain.SubElement", b =>
                {
                    b.Property<int>("SubElementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubElementId"), 1L, 1);

                    b.Property<int>("Element")
                        .HasColumnType("int");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.Property<int?>("WindowId")
                        .HasColumnType("int");

                    b.HasKey("SubElementId");

                    b.HasIndex("WindowId");

                    b.ToTable("SubElements");

                    b.HasData(
                        new
                        {
                            SubElementId = 1,
                            Element = 1,
                            Height = 1850,
                            Type = 0,
                            Width = 1200,
                            WindowId = 1
                        },
                        new
                        {
                            SubElementId = 2,
                            Element = 2,
                            Height = 1850,
                            Type = 1,
                            Width = 800,
                            WindowId = 1
                        },
                        new
                        {
                            SubElementId = 3,
                            Element = 3,
                            Height = 1850,
                            Type = 1,
                            Width = 700,
                            WindowId = 1
                        },
                        new
                        {
                            SubElementId = 4,
                            Element = 1,
                            Height = 2000,
                            Type = 1,
                            Width = 1500,
                            WindowId = 2
                        },
                        new
                        {
                            SubElementId = 5,
                            Element = 1,
                            Height = 2200,
                            Type = 0,
                            Width = 1400,
                            WindowId = 3
                        },
                        new
                        {
                            SubElementId = 6,
                            Element = 2,
                            Height = 2200,
                            Type = 1,
                            Width = 600,
                            WindowId = 3
                        },
                        new
                        {
                            SubElementId = 7,
                            Element = 1,
                            Height = 2000,
                            Type = 1,
                            Width = 1500,
                            WindowId = 4
                        },
                        new
                        {
                            SubElementId = 8,
                            Element = 1,
                            Height = 2000,
                            Type = 1,
                            Width = 1500,
                            WindowId = 4
                        });
                });

            modelBuilder.Entity("SalesOrderManager.Shared.Domain.Window", b =>
                {
                    b.Property<int>("WindowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WindowId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("QuantityOfWindows")
                        .HasColumnType("int");

                    b.Property<int?>("TotalSubElements")
                        .HasColumnType("int");

                    b.HasKey("WindowId");

                    b.HasIndex("OrderId");

                    b.ToTable("Windows");

                    b.HasData(
                        new
                        {
                            WindowId = 1,
                            Name = "A51",
                            OrderId = 1,
                            QuantityOfWindows = 4,
                            TotalSubElements = 3
                        },
                        new
                        {
                            WindowId = 2,
                            Name = "C Zone 5",
                            OrderId = 1,
                            QuantityOfWindows = 2,
                            TotalSubElements = 1
                        },
                        new
                        {
                            WindowId = 3,
                            Name = "GLB",
                            OrderId = 2,
                            QuantityOfWindows = 3,
                            TotalSubElements = 2
                        },
                        new
                        {
                            WindowId = 4,
                            Name = "OHF",
                            OrderId = 2,
                            QuantityOfWindows = 10,
                            TotalSubElements = 2
                        });
                });

            modelBuilder.Entity("SalesOrderManager.Shared.Domain.Employee", b =>
                {
                    b.HasOne("SalesOrderManager.Shared.Domain.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalesOrderManager.Shared.Domain.JobCategory", "JobCategory")
                        .WithMany()
                        .HasForeignKey("JobCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("JobCategory");
                });

            modelBuilder.Entity("SalesOrderManager.Shared.Domain.Order", b =>
                {
                    b.HasOne("SalesOrderManager.Shared.Domain.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId");

                    b.Navigation("State");
                });

            modelBuilder.Entity("SalesOrderManager.Shared.Domain.SubElement", b =>
                {
                    b.HasOne("SalesOrderManager.Shared.Domain.Window", null)
                        .WithMany("SubElements")
                        .HasForeignKey("WindowId");
                });

            modelBuilder.Entity("SalesOrderManager.Shared.Domain.Window", b =>
                {
                    b.HasOne("SalesOrderManager.Shared.Domain.Order", null)
                        .WithMany("Windows")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("SalesOrderManager.Shared.Domain.Order", b =>
                {
                    b.Navigation("Windows");
                });

            modelBuilder.Entity("SalesOrderManager.Shared.Domain.Window", b =>
                {
                    b.Navigation("SubElements");
                });
#pragma warning restore 612, 618
        }
    }
}
